#!/usr/bin/env python3
"""
generate_yaml.py — turn a devices registry into a Home Assistant configuration
block (template proxies + google_assistant exposure).

Usage:
    python3 scripts/generate_yaml.py ha-snippets/devices.example.yaml
    python3 scripts/generate_yaml.py my-devices.yaml > my-config-block.yaml

The output is a single YAML block ready to paste into configuration.yaml.

Input shape (see ha-snippets/devices.example.yaml for a full example):

    google:
      project_id: your-google-project-id
      service_account_include: SERVICE_ACCOUNT.json

    home_assistant:
      external_url: "https://YOUR_HOST"
      internal_url: "http://YOUR_LAN_IP:8123"

    devices:
      - name: "TV LED Back Light"
        ble_source: light.govee_light
        proxy_id: tv_led_back_light_google
        room: Living Room

This script has zero third-party dependencies — it ships with Python 3.8+.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

try:
    import yaml  # type: ignore
except ImportError:
    sys.stderr.write(
        "ERROR: PyYAML is required.\n"
        "  Install with: pip install pyyaml\n"
        "  (or on Debian/Ubuntu: sudo apt install python3-yaml)\n"
    )
    sys.exit(2)


def render_template_light(device: dict[str, str]) -> str:
    """Render one template-light block for a single device."""
    name = device["name"]
    ble = device["ble_source"]
    proxy = device["proxy_id"]
    return f"""      - default_entity_id: light.{proxy}
        unique_id: {proxy}
        name: "{name} Google"
        availability: "{{{{ states('{ble}') not in ['unknown', 'unavailable'] }}}}"
        state: "{{{{ is_state('{ble}', 'on') }}}}"
        level: "{{{{ state_attr('{ble}', 'brightness') | default(0, true) | int }}}}"
        hs: "{{{{ state_attr('{ble}', 'hs_color') or (0, 0) }}}}"
        turn_on:
          action: light.turn_on
          target: {{ entity_id: {ble} }}
        turn_off:
          action: light.turn_off
          target: {{ entity_id: {ble} }}
        set_level:
          action: light.turn_on
          target: {{ entity_id: {ble} }}
          data:
            brightness: "{{{{ brightness }}}}"
        set_hs:
          action: light.turn_on
          target: {{ entity_id: {ble} }}
          data:
            hs_color: ["{{{{ h }}}}", "{{{{ s }}}}"]
            brightness: "{{{{ brightness | default(state_attr('{ble}', 'brightness') | default(255, true), true) }}}}"
"""


def render_google_entity(device: dict[str, str]) -> str:
    """Render one google_assistant.entity_config entry."""
    proxy = device["proxy_id"]
    name = device["name"]
    room = device["room"]
    return (
        f"    light.{proxy}:\n"
        f"      expose: true\n"
        f"      name: {name}\n"
        f"      room: {room}\n"
    )


def validate(cfg: dict[str, Any]) -> None:
    if "devices" not in cfg or not cfg["devices"]:
        raise SystemExit("ERROR: devices list is empty")
    seen_proxies: set[str] = set()
    seen_sources: set[str] = set()
    for i, d in enumerate(cfg["devices"]):
        for k in ("name", "ble_source", "proxy_id", "room"):
            if not d.get(k):
                raise SystemExit(f"ERROR: device #{i + 1} missing field '{k}'")
        if d["proxy_id"] in seen_proxies:
            raise SystemExit(f"ERROR: duplicate proxy_id '{d['proxy_id']}'")
        if d["ble_source"] in seen_sources:
            raise SystemExit(f"ERROR: duplicate ble_source '{d['ble_source']}'")
        seen_proxies.add(d["proxy_id"])
        seen_sources.add(d["ble_source"])


def render_config(cfg: dict[str, Any]) -> str:
    google = cfg.get("google", {})
    ha = cfg.get("home_assistant", {})
    project_id = google.get("project_id", "your-google-project-id")
    sa_include = google.get("service_account_include", "SERVICE_ACCOUNT.json")
    external_url = ha.get("external_url", "https://YOUR_HOST")
    internal_url = ha.get("internal_url", "http://YOUR_LAN_IP:8123")

    template_blocks = "\n".join(render_template_light(d) for d in cfg["devices"])
    google_blocks = "".join(render_google_entity(d) for d in cfg["devices"])
    n = len(cfg["devices"])

    header = (
        "# Generated by scripts/generate_yaml.py\n"
        f"# Devices: {n}\n"
        "# Paste this entire block into your Home Assistant configuration.yaml.\n"
        "# Edit URLs and project_id if you used placeholders in devices.yaml.\n\n"
    )

    return (
        header
        + f'homeassistant:\n  external_url: "{external_url}"\n  internal_url: "{internal_url}"\n\n'
        + "template:\n  - light:\n"
        + template_blocks
        + "\n"
        + "google_assistant:\n"
        + f"  project_id: {project_id}\n"
        + f"  service_account: !include {sa_include}\n"
        + "  report_state: true\n"
        + "  expose_by_default: false\n"
        + "  entity_config:\n"
        + google_blocks
    )


def main() -> int:
    p = argparse.ArgumentParser(
        description="Generate a Home Assistant YAML block from a devices registry.",
    )
    p.add_argument("devices_yaml", type=Path, help="Path to devices YAML file")
    p.add_argument(
        "-o",
        "--output",
        type=Path,
        help="Write output to file instead of stdout",
    )
    args = p.parse_args()

    if not args.devices_yaml.exists():
        sys.stderr.write(f"ERROR: file not found: {args.devices_yaml}\n")
        return 2

    with args.devices_yaml.open() as f:
        cfg = yaml.safe_load(f)

    validate(cfg)
    rendered = render_config(cfg)

    if args.output:
        args.output.write_text(rendered)
        sys.stderr.write(f"Wrote {len(cfg['devices'])} device(s) -> {args.output}\n")
    else:
        sys.stdout.write(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
